### PR TITLE
fs: switch to d_splice_alias()

### PR DESCRIPTION
**Pull request by bhundven**
During the 3.19 merge window, two commits in Linus's tree:
b5ae6b15bd73e35b129408755a0804287a87e041
=====
merge d_materialise_unique() into d_splice_alias()
=====
and
41d28bca2da4bd75a8915c1ccf2cacf7f4a2e531
=====
switch d_materialise_unique() users to d_splice_alias()
=====

...requires us to switch to d_splice_alias().

Signed-off-by: Bryan Hundven <bryanhundven@gmail.com>

### CODE REVIEW

**Comment by gregkh** [comment]
Please send this to the systemd mailing list so we can take the patch properly, this repo is just a mirror of the google one...

**Comment by bhundven** [comment]
Just to verify before I send the patch to the wrong list, you mean the systemd-devel mailing list?

**Comment by gregkh** [comment]
yes, that's the one, I don't know of any other systemd specific mailing list, are there others?

**Comment by bhundven** [comment]
Nope, just my lack of never sending a patch to them. "Trust, but verify."

**Pull request closed without merging**
